### ISSUE TITLE
API did not pick up dropped trial

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#135]
This trial dropped off the overdue list during the March 20th data processing as a result of changing its phase to "Phase 1" but it was not picked up by the API:

https://clinicaltrials.gov/ct2/show/study/NCT02086526

These two trials were correctly identified:

https://clinicaltrials.gov/ct2/show/NCT00874614 (Got Certificate of Delay)

https://clinicaltrials.gov/ct2/show/NCT00026208 (Submitted Results)

**Comment by sebbacon** [comment]
OK, so it stopped being overdue because it is no longer a pACT.

In the data, the status is still `overdue`.

There are two things arising from this:

1. Need to include no-longer-ACT trials in our delta statistics
2. Need to indicate trials that are no-longer-ACTs on their respective pages (they don't appear in searches but can still be accessed via a direct link, and will still be indexed by spiders)
