### ISSUE TITLE
"no-longer-overdue" filter broken for things that stop being pACTs

### ISSUE THREAD

**Issue by NickCEBM** [ebmdatalab/clinicaltrials-act-tracker#141]
This trial is no longer a "pACT" because they updated their completion to be December 2016 which is pre-final rule and therefore no longer covered by our tracker.

https://clinicaltrials.gov/ct2/show/NCT02505867

The api did not pick this up as a "dropped" trial.

**Comment by NickCEBM** [comment]
This problem persists in the API. Another example:

https://staging-fdaaa.ebmdatalab.net/trial/NCT01707992/

**Comment by NickCEBM** [comment]
This one is a bit of an odd situation I am looking into, but for future reference NCT02593760 changed phase from Phase 1/2 to Phase 1 in the data. This wasn't picked up by the API.

**Comment by sebbacon** [comment]
When you say "is not picked up in the API", do you mean it doesn't appear in the list of things that are no longer overdue today?

So, for example, the first trial in this issue was overdue, and then stopped being a pACT, so should have appeared in that list?

**Comment by sebbacon** [comment]
Re-reading the code, those examples should have worked. However, we can only define "no longer overdue today" as things which changed since the previous update.

So your first example above was noted to be no longer an ACT on 5th April.  It should therefore have appeared in the API list of things which were no longer overdue "today" until the next update was run. If you looked at the API on 6th April *after* the update on that day, it would not have appeared.

**Comment by sebbacon** [comment]
It's going to be hard to debug this without a *fresh* example. Next time it happens, be sure to (a) notify me and (b) don't do any updates until I've had a look at it.

**Comment by NickCEBM** [comment]
Seb, have a fresh example of this (put it in the wrong issue on Friday). Details below:

https://clinicaltrials.gov/ct2/show/study/NCT02116959

This issue showed up again today with this trial. Changed from "N/A" to "Phase 1" so it dropped from being a pACT and then didn't show up on the API as dropped. I believe you said next time this happens to call it out and not deploy so I will do that!
