### ISSUE TITLE
Error in load_data pipeline

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#201]
```
Error in FDAAA import: Traceback (most recent call last):
 File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/management/commands/load_data.py", line 657, in handle
   convert_to_csv()
 File "/var/www/fdaaa_staging/clinicaltrials-act-tracker/clinicaltrials/frontend/management/commands/load_data.py", line 487, in convert_to_csv
   and td["available_completion_date"] >= effective_date
TypeError: unorderable types: NoneType() >= datetime.date()
```

**Comment by sebbacon** [comment]
@NickCEBM judging from [your PR](https://github.com/ebmdatalab/clinicaltrials-act-tracker/pull/200) the desired behaviour is that when there is no start date, a trial is never flagged as a PACT or ACT.  Is that correct?

**Comment by NickCEBM** [comment]
I think that would have to be the case because trials with no start date are either:

1. Trials with all their information redacted, in which case we can't determine anything about them or

2. Unable to be put in the pACT or ACT bucket anyway. With no start date we don't know which criteria to apply.

**Comment by NickCEBM** [comment]
One a very quick look, the amount of trials that are even close to being ACTs or pACTs with no Start Date is around 3, so a safe and probably necessary exclusion to make it work logically.
