### ISSUE TITLE
SQL Review: ACT flag doesn't contain not-before completion date logic

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/clinicaltrials-act-tracker#67]
![image](https://user-images.githubusercontent.com/211271/36369591-a793b4c2-1553-11e8-8de5-3d4f2b6658a9.png)

**Comment by NickCEBM** [comment]
This is ignored, and detailed in the paper.

Anything we are calling an ACT has to, logically, have a completion date after January 18, 2017 because having a Start Date of January 18, 2017 is one of our criteria. Because of this, we believe we can safely ignore this criteria as redundant. 

From the paper directly:

> Table 1 also identify post-2008 completion dates as as required criteria for both pACTs and ACTs. All pACTs and ACTs relevant to our tracker will have completion dates on or after January 18, 2017 so this criteria was unnecessary for our purposes. While the official ACT/pACT criteria also includes trials with no completion date specified, it is impossible to track Final Rule compliance without a completion date and therefore these trials cannot be included in our tracker.
